sudo: false
language: go
os: linux

go:
  - master
  - 1.12.x
  - 1.11.x

git:
  depth: 5
  submodules: false

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      go: 1.x
    - os: windows
      go: 1.x
    - os: linux
      go: 1.x
      env:
        - ALFRED_TEST="-race"

install:
  - ./build.sh

script:
  - ./check.sh
