# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.12.0"

[[override]]
  name = "golang.org/x/crypto"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.10.0"
