#!/bin/bash
SRCDIR=${SRCDIR:-'/SRCDIR/notset'}
cd ${SRCDIR}

if test -z "${ALFRED_UMASK}"; then
	echo 'ALFRED_UMASK not set'
	exit 1
fi
umask ${ALFRED_UMASK}

echo "-- login"
echo "--     user $(id -a)"
echo "--     umask $(umask)"
echo "--     workdir $(pwd)"
echo "--     docker cmd ${DOCKER_CMD}"

if test -n "${DOCKER_CMD}"; then
	if test -x ./docker/container/${DOCKER_CMD}.sh; then
		exec ./docker/container/${DOCKER_CMD}.sh
	else
		echo "E: ./docker/container/${DOCKER_CMD}.sh not found" >&2
	fi
fi
