title: alfred
description: Alfred, the house master (mayordomo).
email: jrmsdev@gmail.com

repository: jrmsdev/alfred
theme: jekyll-theme-minimal

# Exclude from processing.
exclude:
  - .gitignore
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - docker/build.sh
  - docker/run.sh
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
